name: Launcher

on:
  workflow_dispatch:

jobs:
  push:
      runs-on: ubuntu-latest
      steps:
        - run: gh workflow run test.yml --repo EdissonPena/Nexos
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
